import { ECategory, EUserRole, EUserStatus } from "@/types/enum";

export const mockStats = {
    totalVisitors: 12543,
    uniqueVisitors: 8742,
    pageViews: 45892,
    avgSessionDuration: "3m 42s",
    bounceRate: "32.4%",
    topPages: [
        { title: "Homepage", views: 12450 },
        { title: "Programs", views: 8765 },
        { title: "Jobs", views: 6543 },
        { title: "Contact", views: 4321 },
        { title: "FAQ", views: 3210 },
    ],
    recentActivity: [
        { id: 1, action: "New user registered", time: "2 min ago" },
        { id: 2, action: "Job application submitted", time: "15 min ago" },
        { id: 3, action: "Contact form submitted", time: "1 hour ago" },
        { id: 4, action: "New blog post published", time: "3 hours ago" },
    ],
};

// Mock Users Data
export const mockUsers: IUser[] = [
    {
        id: "user-1",
        username: "johndoe",
        email: "john.doe@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-2",
        username: "janesmith",
        email: "jane.smith@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-3",
        username: "mikejohnson",
        email: "mike.johnson@example.com",
        avatarUrl: "",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-4",
        username: "sarahwilson",
        email: "sarah.wilson@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-5",
        username: "davidbrown",
        email: "david.brown@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-6",
        username: "emilydavis",
        email: "emily.davis@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-7",
        username: "alexgarcia",
        email: "alex.garcia@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-8",
        username: "lisachen",
        email: "lisa.chen@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-9",
        username: "robertlee",
        email: "robert.lee@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-10",
        username: "amandataylor",
        email: "amanda.taylor@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-11",
        username: "chrisanderson",
        email: "chris.anderson@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-01T00:00:00Z",
        updatedAt: "2023-02-01T00:00:00Z",
    },
    {
        id: "user-12",
        username: "laurajones",
        email: "laura.jones@example.com",
        avatarUrl: "",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-02T00:00:00Z",
        updatedAt: "2023-02-02T00:00:00Z",
    },
    {
        id: "user-13",
        username: "matthewmartinez",
        email: "matthew.martinez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-02-03T00:00:00Z",
        updatedAt: "2023-02-03T00:00:00Z",
    },
    {
        id: "user-14",
        username: "jessicawilliams",
        email: "jessica.williams@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-04T00:00:00Z",
        updatedAt: "2023-02-04T00:00:00Z",
    },
    {
        id: "user-15",
        username: "danielgarcia",
        email: "daniel.garcia@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-02-05T00:00:00Z",
        updatedAt: "2023-02-05T00:00:00Z",
    },
    {
        id: "user-16",
        username: "ashleyrodriguez",
        email: "ashley.rodriguez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-06T00:00:00Z",
        updatedAt: "2023-02-06T00:00:00Z",
    },
    {
        id: "user-17",
        username: "joshuamartinez",
        email: "joshua.martinez@example.com",
        avatarUrl: "",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-07T00:00:00Z",
        updatedAt: "2023-02-07T00:00:00Z",
    },
    {
        id: "user-18",
        username: "sophiahernandez",
        email: "sophia.hernandez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-02-08T00:00:00Z",
        updatedAt: "2023-02-08T00:00:00Z",
    },
    {
        id: "user-19",
        username: "andrewlopez",
        email: "andrew.lopez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-09T00:00:00Z",
        updatedAt: "2023-02-09T00:00:00Z",
    },
    {
        id: "user-20",
        username: "isabellagonzalez",
        email: "isabella.gonzalez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-02-10T00:00:00Z",
        updatedAt: "2023-02-10T00:00:00Z",
    },
    {
        id: "user-21",
        username: "ethanperez",
        email: "ethan.perez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-11T00:00:00Z",
        updatedAt: "2023-02-11T00:00:00Z",
    },
    {
        id: "user-22",
        username: "oliviasanchez",
        email: "olivia.sanchez@example.com",
        avatarUrl: "",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-12T00:00:00Z",
        updatedAt: "2023-02-12T00:00:00Z",
    },
    {
        id: "user-23",
        username: "noahramirez",
        email: "noah.ramirez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-02-13T00:00:00Z",
        updatedAt: "2023-02-13T00:00:00Z",
    },
    {
        id: "user-24",
        username: "emmatorres",
        email: "emma.torres@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-14T00:00:00Z",
        updatedAt: "2023-02-14T00:00:00Z",
    },
    {
        id: "user-25",
        username: "liamflores",
        email: "liam.flores@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-02-15T00:00:00Z",
        updatedAt: "2023-02-15T00:00:00Z",
    },
    {
        id: "user-26",
        username: "avagonzalez",
        email: "ava.gonzalez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-16T00:00:00Z",
        updatedAt: "2023-02-16T00:00:00Z",
    },
    {
        id: "user-27",
        username: "jacobrivera",
        email: "jacob.rivera@example.com",
        avatarUrl: "",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-17T00:00:00Z",
        updatedAt: "2023-02-17T00:00:00Z",
    },
    {
        id: "user-28",
        username: "charlottegomez",
        email: "charlotte.gomez@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-02-18T00:00:00Z",
        updatedAt: "2023-02-18T00:00:00Z",
    },
    {
        id: "user-29",
        username: "michaeldiaz",
        email: "michael.diaz@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-02-19T00:00:00Z",
        updatedAt: "2023-02-19T00:00:00Z",
    },
    {
        id: "user-30",
        username: "harpermoreno",
        email: "harper.moreno@example.com",
        avatarUrl: "",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-02-20T00:00:00Z",
        updatedAt: "2023-02-20T00:00:00Z",
    },
];

// Mock Blogs Data
export const mockBlogs: IBlog[] = [
    {
        id: "blog-1",
        title: "Getting Started with Next.js 14",
        description: "A comprehensive guide to building modern web applications with Next.js 14",
        content: "Next.js 14 introduces several exciting features including improved performance, better developer experience, and enhanced server components. In this article, we'll explore the key features and how to get started with your first Next.js project...",
        thumbnailUrl: "",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[2],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: "2024-01-10T10:00:00Z",
    },
    {
        id: "blog-2",
        title: "10 Healthy Habits for a Better Life",
        description: "Simple daily habits that can transform your health and wellness",
        content: "Living a healthy lifestyle doesn't have to be complicated. By incorporating these 10 simple habits into your daily routine, you can significantly improve your physical and mental well-being. From morning routines to evening practices, discover practical tips that fit into any busy schedule...",
        thumbnailUrl: "",
        category: ECategory.HEALTH,
        author: mockUsers[1],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-12T14:30:00Z",
        updatedAt: "2024-01-12T14:30:00Z",
    },
    {
        id: "blog-3",
        title: "Understanding Cryptocurrency Investment in 2024",
        description: "A beginner's guide to cryptocurrency markets and investment strategies",
        content: "Cryptocurrency has evolved from a niche technology to a mainstream investment option. This comprehensive guide covers the fundamentals of blockchain technology, popular cryptocurrencies, and smart investment strategies for beginners. Learn how to navigate the volatile crypto market safely...",
        thumbnailUrl: "",
        category: ECategory.FINANCE,
        author: mockUsers[0],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-08T09:15:00Z",
        updatedAt: "2024-01-08T09:15:00Z",
    },
    {
        id: "blog-4",
        title: "Top 10 Travel Destinations for 2024",
        description: "Explore the most beautiful and exciting places to visit this year",
        content: "From pristine beaches to historic cities, discover the top travel destinations that should be on your bucket list for 2024. Each destination offers unique experiences, rich culture, and unforgettable memories. Get insider tips on the best times to visit, local attractions, and hidden gems...",
        thumbnailUrl: "",
        category: ECategory.TRAVEL,
        author: mockUsers[3],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-15T16:45:00Z",
        updatedAt: "2024-01-15T16:45:00Z",
    },
    {
        id: "blog-5",
        title: "The Future of AI in Education",
        description: "How artificial intelligence is transforming learning experiences",
        content: "Artificial Intelligence is revolutionizing education by personalizing learning experiences, automating administrative tasks, and providing intelligent tutoring systems. Explore how AI-powered tools are making education more accessible and effective for students worldwide...",
        thumbnailUrl: "",
        category: ECategory.EDUCATION,
        author: mockUsers[5],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-11T11:20:00Z",
        updatedAt: "2024-01-11T11:20:00Z",
    },
    {
        id: "blog-6",
        title: "The Best Movies and TV Shows of 2023",
        description: "A review of the most captivating entertainment from last year",
        content: "2023 was an incredible year for entertainment, featuring blockbuster movies, binge-worthy TV series, and groundbreaking performances. From superhero epics to intimate dramas, discover the content that defined the year and what made them so special...",
        thumbnailUrl: "",
        category: ECategory.ENTERTAINMENT,
        author: mockUsers[6],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-05T13:00:00Z",
        updatedAt: "2024-01-05T13:00:00Z",
    },
    {
        id: "blog-7",
        title: "Effective Study Techniques for Students",
        description: "Proven methods to improve retention and academic performance",
        content: "Success in academics isn't just about spending hours studying—it's about studying smart. Learn evidence-based study techniques including spaced repetition, active recall, and the Pomodoro Technique. These methods are backed by cognitive science and can help you learn more efficiently...",
        thumbnailUrl: "",
        category: ECategory.STUDY,
        author: mockUsers[7],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-14T08:30:00Z",
        updatedAt: "2024-01-14T08:30:00Z",
    },
    {
        id: "blog-8",
        title: "Building Scalable Microservices with Spring Boot",
        description: "Best practices for developing enterprise-grade microservices",
        content: "Microservices architecture has become the standard for building scalable applications. This guide covers essential patterns and practices for developing robust microservices using Spring Boot, including service discovery, API gateways, and distributed tracing...",
        thumbnailUrl: "",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[2],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-13T15:00:00Z",
        updatedAt: "2024-01-13T15:00:00Z",
    },
    {
        id: "blog-9",
        title: "Mental Health Awareness: Breaking the Stigma",
        description: "Understanding and addressing mental health in modern society",
        content: "Mental health is as important as physical health, yet stigma continues to prevent many from seeking help. This article explores common mental health conditions, the importance of seeking professional support, and how society can create a more understanding environment...",
        thumbnailUrl: "",
        category: ECategory.HEALTH,
        author: mockUsers[9],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-09T12:00:00Z",
        updatedAt: "2024-01-09T12:00:00Z",
    },
    {
        id: "blog-10",
        title: "Personal Finance Management Tips",
        description: "Smart strategies for saving, investing, and achieving financial freedom",
        content: "Financial literacy is crucial for long-term success and security. Learn practical tips for budgeting, building an emergency fund, investing wisely, and planning for retirement. These fundamental principles can help anyone take control of their financial future...",
        thumbnailUrl: "",
        category: ECategory.FINANCE,
        author: mockUsers[4],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-07T10:45:00Z",
        updatedAt: "2024-01-07T10:45:00Z",
    },
    {
        id: "blog-11",
        title: "Mastering React Hooks",
        description: "A deep dive into React Hooks and their practical applications",
        content: "React Hooks have revolutionized the way we write React components. This comprehensive guide covers all the built-in hooks and how to create custom hooks for reusable logic...",
        thumbnailUrl: "",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[0],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-16T09:00:00Z",
        updatedAt: "2024-01-16T09:00:00Z",
    },
    {
        id: "blog-12",
        title: "Yoga for Beginners",
        description: "Start your yoga journey with these essential poses and techniques",
        content: "Yoga is more than just physical exercise—it's a holistic practice that benefits both body and mind. Learn the fundamental poses, breathing techniques, and meditation practices...",
        thumbnailUrl: "",
        category: ECategory.HEALTH,
        author: mockUsers[1],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-17T11:30:00Z",
        updatedAt: "2024-01-17T11:30:00Z",
    },
    {
        id: "blog-13",
        title: "Stock Market Basics",
        description: "Understanding the fundamentals of stock market investing",
        content: "The stock market can seem intimidating, but with the right knowledge, anyone can start investing. Learn about stocks, bonds, ETFs, and how to build a diversified portfolio...",
        thumbnailUrl: "",
        category: ECategory.FINANCE,
        author: mockUsers[3],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-18T14:15:00Z",
        updatedAt: "2024-01-18T14:15:00Z",
    },
    {
        id: "blog-14",
        title: "Hidden Gems in Europe",
        description: "Discover lesser-known destinations that are worth the trip",
        content: "Beyond the popular tourist spots, Europe is full of hidden gems waiting to be explored. From charming villages to pristine natural wonders, find your next adventure...",
        thumbnailUrl: "",
        category: ECategory.TRAVEL,
        author: mockUsers[5],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-19T16:00:00Z",
        updatedAt: "2024-01-19T16:00:00Z",
    },
    {
        id: "blog-15",
        title: "Online Learning Platforms",
        description: "The best platforms for continuous education and skill development",
        content: "In today's fast-paced world, continuous learning is essential. Explore the top online learning platforms offering courses from world-class institutions...",
        thumbnailUrl: "",
        category: ECategory.EDUCATION,
        author: mockUsers[6],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-20T10:45:00Z",
        updatedAt: "2024-01-20T10:45:00Z",
    },
    {
        id: "blog-16",
        title: "Classic Films You Must Watch",
        description: "Timeless movies that have shaped cinema history",
        content: "Cinema has given us countless masterpieces that continue to inspire and entertain. Discover the films that every movie lover should experience at least once...",
        thumbnailUrl: "",
        category: ECategory.ENTERTAINMENT,
        author: mockUsers[7],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-21T13:20:00Z",
        updatedAt: "2024-01-21T13:20:00Z",
    },
    {
        id: "blog-17",
        title: "Memory Techniques",
        description: "Improve your memory with proven mnemonic devices",
        content: "A good memory is a powerful tool for academic success and daily life. Learn various memory techniques including the method of loci, peg system, and visualization...",
        thumbnailUrl: "",
        category: ECategory.STUDY,
        author: mockUsers[8],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-22T08:30:00Z",
        updatedAt: "2024-01-22T08:30:00Z",
    },
    {
        id: "blog-18",
        title: "Docker for Developers",
        description: "Containerization made simple for software development",
        content: "Docker has transformed how we develop and deploy applications. Learn the basics of containerization, Docker commands, and best practices for development workflows...",
        thumbnailUrl: "",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[9],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-23T15:10:00Z",
        updatedAt: "2024-01-23T15:10:00Z",
    },
    {
        id: "blog-19",
        title: "Mindfulness Meditation",
        description: "Techniques to reduce stress and improve mental clarity",
        content: "Mindfulness meditation can help you manage stress, improve focus, and enhance overall well-being. Learn different meditation techniques suitable for beginners...",
        thumbnailUrl: "",
        category: ECategory.HEALTH,
        author: mockUsers[0],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-24T12:00:00Z",
        updatedAt: "2024-01-24T12:00:00Z",
    },
    {
        id: "blog-20",
        title: "Real Estate Investment",
        description: "A beginner's guide to investing in property",
        content: "Real estate can be a lucrative investment option. Learn about different types of properties, financing options, and strategies for successful real estate investing...",
        thumbnailUrl: "",
        category: ECategory.FINANCE,
        author: mockUsers[1],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-25T09:45:00Z",
        updatedAt: "2024-01-25T09:45:00Z",
    },
    {
        id: "blog-21",
        title: "Solo Travel Tips",
        description: "Essential advice for traveling alone safely and enjoyably",
        content: "Solo travel can be incredibly rewarding. Learn how to plan your trip, stay safe, meet fellow travelers, and make the most of your solo adventures...",
        thumbnailUrl: "",
        category: ECategory.TRAVEL,
        author: mockUsers[2],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-26T14:30:00Z",
        updatedAt: "2024-01-26T14:30:00Z",
    },
    {
        id: "blog-22",
        title: "STEM Education",
        description: "The importance of science, technology, engineering, and math in education",
        content: "STEM education is crucial for preparing students for the future. Explore the benefits of STEM learning and ways to encourage STEM interest in young minds...",
        thumbnailUrl: "",
        category: ECategory.EDUCATION,
        author: mockUsers[3],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-27T11:15:00Z",
        updatedAt: "2024-01-27T11:15:00Z",
    },
    {
        id: "blog-23",
        title: "Indie Music Scene",
        description: "Discovering hidden talents in the independent music world",
        content: "The indie music scene is full of creativity and originality. Learn about emerging artists, underground genres, and how to support independent musicians...",
        thumbnailUrl: "",
        category: ECategory.ENTERTAINMENT,
        author: mockUsers[4],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-28T16:45:00Z",
        updatedAt: "2024-01-28T16:45:00Z",
    },
    {
        id: "blog-24",
        title: "Time Management Strategies",
        description: "Effective techniques to make the most of your time",
        content: "Time management is key to productivity and success. Learn various strategies including prioritization, goal setting, and avoiding procrastination...",
        thumbnailUrl: "",
        category: ECategory.STUDY,
        author: mockUsers[5],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-29T10:00:00Z",
        updatedAt: "2024-01-29T10:00:00Z",
    },
    {
        id: "blog-25",
        title: "Kubernetes Fundamentals",
        description: "Understanding container orchestration with Kubernetes",
        content: "Kubernetes is the leading platform for container orchestration. Learn the core concepts, architecture, and how to deploy applications at scale...",
        thumbnailUrl: "",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[6],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-30T13:30:00Z",
        updatedAt: "2024-01-30T13:30:00Z",
    },
    {
        id: "blog-26",
        title: "Nutrition Myths",
        description: "Separating fact from fiction in nutrition science",
        content: "There's a lot of misinformation about nutrition. Learn to distinguish between myths and evidence-based facts to make better dietary choices...",
        thumbnailUrl: "",
        category: ECategory.HEALTH,
        author: mockUsers[7],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-01-31T15:20:00Z",
        updatedAt: "2024-01-31T15:20:00Z",
    },
    {
        id: "blog-27",
        title: "Cryptocurrency Trading",
        description: "Advanced strategies for crypto trading",
        content: "Beyond basic investing, learn about trading strategies, technical analysis, and risk management in the cryptocurrency markets...",
        thumbnailUrl: "",
        category: ECategory.FINANCE,
        author: mockUsers[8],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-02-01T11:45:00Z",
        updatedAt: "2024-02-01T11:45:00Z",
    },
    {
        id: "blog-28",
        title: "Cultural Immersion Travel",
        description: "How to truly experience local cultures while traveling",
        content: "Traveling is about more than sightseeing. Learn how to immerse yourself in local cultures, respect traditions, and create meaningful connections...",
        thumbnailUrl: "",
        category: ECategory.TRAVEL,
        author: mockUsers[9],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-02-02T14:10:00Z",
        updatedAt: "2024-02-02T14:10:00Z",
    },
    {
        id: "blog-29",
        title: "Coding Bootcamps",
        description: "Are coding bootcamps worth it for career changers?",
        content: "Coding bootcamps offer accelerated learning paths for those wanting to enter tech. Explore the pros, cons, and what to look for in a quality program...",
        thumbnailUrl: "",
        category: ECategory.EDUCATION,
        author: mockUsers[0],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-02-03T09:30:00Z",
        updatedAt: "2024-02-03T09:30:00Z",
    },
    {
        id: "blog-30",
        title: "Board Games Renaissance",
        description: "The resurgence of board games in the digital age",
        content: "Board games are experiencing a renaissance. Discover why analog games are thriving, popular titles, and the social benefits of tabletop gaming...",
        thumbnailUrl: "",
        category: ECategory.ENTERTAINMENT,
        author: mockUsers[1],
        comments: [],
        isVisibility: true,
        isSaved: false,
        createdAt: "2024-02-04T16:00:00Z",
        updatedAt: "2024-02-04T16:00:00Z",
    },
];


