import { ECategory, EUserRole, EUserStatus } from "@/types/enum";

export const mockStats = {
    totalVisitors: 12543,
    uniqueVisitors: 8742,
    pageViews: 45892,
    avgSessionDuration: "3m 42s",
    bounceRate: "32.4%",
    topPages: [
        { title: "Homepage", views: 12450 },
        { title: "Programs", views: 8765 },
        { title: "Jobs", views: 6543 },
        { title: "Contact", views: 4321 },
        { title: "FAQ", views: 3210 },
    ],
    recentActivity: [
        { id: 1, action: "New user registered", time: "2 min ago" },
        { id: 2, action: "Job application submitted", time: "15 min ago" },
        { id: 3, action: "Contact form submitted", time: "1 hour ago" },
        { id: 4, action: "New blog post published", time: "3 hours ago" },
    ],
};

// Mock Users Data
export const mockUsers: IUser[] = [
    {
        id: "user-1",
        username: "johndoe",
        email: "john.doe@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-2",
        username: "janesmith",
        email: "jane.smith@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-3",
        username: "mikejohnson",
        email: "mike.johnson@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.ADMIN,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-4",
        username: "sarahwilson",
        email: "sarah.wilson@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-5",
        username: "davidbrown",
        email: "david.brown@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.PENDING,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-6",
        username: "emilydavis",
        email: "emily.davis@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-7",
        username: "alexgarcia",
        email: "alex.garcia@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-8",
        username: "lisachen",
        email: "lisa.chen@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-9",
        username: "robertlee",
        email: "robert.lee@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.BANNED,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "user-10",
        username: "amandataylor",
        email: "amanda.taylor@example.com",
        avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
        role: EUserRole.USER,
        status: EUserStatus.ACTIVE,
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
];

// Mock Blogs Data
export const mockBlogs: IBlog[] = [
    {
        id: "blog-1",
        title: "Getting Started with Next.js 14",
        description: "A comprehensive guide to building modern web applications with Next.js 14",
        content: "Next.js 14 introduces several exciting features including improved performance, better developer experience, and enhanced server components. In this article, we'll explore the key features and how to get started with your first Next.js project...",
        thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[2], // Mike Johnson (Admin)
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: "2024-01-10T10:00:00Z",
    },
    {
        id: "blog-2",
        title: "10 Healthy Habits for a Better Life",
        description: "Simple daily habits that can transform your health and wellness",
        content: "Living a healthy lifestyle doesn't have to be complicated. By incorporating these 10 simple habits into your daily routine, you can significantly improve your physical and mental well-being. From morning routines to evening practices, discover practical tips that fit into any busy schedule...",
        thumbnailUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=400&fit=crop",
        category: ECategory.HEALTH,
        author: mockUsers[1], // Jane Smith
        createdAt: "2024-01-12T14:30:00Z",
        updatedAt: "2024-01-12T14:30:00Z",
    },
    {
        id: "blog-3",
        title: "Understanding Cryptocurrency Investment in 2024",
        description: "A beginner's guide to cryptocurrency markets and investment strategies",
        content: "Cryptocurrency has evolved from a niche technology to a mainstream investment option. This comprehensive guide covers the fundamentals of blockchain technology, popular cryptocurrencies, and smart investment strategies for beginners. Learn how to navigate the volatile crypto market safely...",
        thumbnailUrl: "https://images.unsplash.com/photo-1605792657660-596af9009e82?w=800&h=400&fit=crop",
        category: ECategory.FINANCE,
        author: mockUsers[0], // John Doe
        createdAt: "2024-01-08T09:15:00Z",
        updatedAt: "2024-01-08T09:15:00Z",
    },
    {
        id: "blog-4",
        title: "Top 10 Travel Destinations for 2024",
        description: "Explore the most beautiful and exciting places to visit this year",
        content: "From pristine beaches to historic cities, discover the top travel destinations that should be on your bucket list for 2024. Each destination offers unique experiences, rich culture, and unforgettable memories. Get insider tips on the best times to visit, local attractions, and hidden gems...",
        thumbnailUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=400&fit=crop",
        category: ECategory.TRAVEL,
        author: mockUsers[3], // Sarah Wilson
        createdAt: "2024-01-15T16:45:00Z",
        updatedAt: "2024-01-15T16:45:00Z",
    },
    {
        id: "blog-5",
        title: "The Future of AI in Education",
        description: "How artificial intelligence is transforming learning experiences",
        content: "Artificial Intelligence is revolutionizing education by personalizing learning experiences, automating administrative tasks, and providing intelligent tutoring systems. Explore how AI-powered tools are making education more accessible and effective for students worldwide...",
        thumbnailUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop",
        category: ECategory.EDUCATION,
        author: mockUsers[5], // Emily Davis
        createdAt: "2024-01-11T11:20:00Z",
        updatedAt: "2024-01-11T11:20:00Z",
    },
    {
        id: "blog-6",
        title: "The Best Movies and TV Shows of 2023",
        description: "A review of the most captivating entertainment from last year",
        content: "2023 was an incredible year for entertainment, featuring blockbuster movies, binge-worthy TV series, and groundbreaking performances. From superhero epics to intimate dramas, discover the content that defined the year and what made them so special...",
        thumbnailUrl: "https://images.unsplash.com/photo-1574267432644-f84f6e59ca9e?w=800&h=400&fit=crop",
        category: ECategory.ENTERTAINMENT,
        author: mockUsers[6], // Alex Garcia
        createdAt: "2024-01-05T13:00:00Z",
        updatedAt: "2024-01-05T13:00:00Z",
    },
    {
        id: "blog-7",
        title: "Effective Study Techniques for Students",
        description: "Proven methods to improve retention and academic performance",
        content: "Success in academics isn't just about spending hours studying—it's about studying smart. Learn evidence-based study techniques including spaced repetition, active recall, and the Pomodoro Technique. These methods are backed by cognitive science and can help you learn more efficiently...",
        thumbnailUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=400&fit=crop",
        category: ECategory.STUDY,
        author: mockUsers[7], // Lisa Chen
        createdAt: "2024-01-14T08:30:00Z",
        updatedAt: "2024-01-14T08:30:00Z",
    },
    {
        id: "blog-8",
        title: "Building Scalable Microservices with Spring Boot",
        description: "Best practices for developing enterprise-grade microservices",
        content: "Microservices architecture has become the standard for building scalable applications. This guide covers essential patterns and practices for developing robust microservices using Spring Boot, including service discovery, API gateways, and distributed tracing...",
        thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop",
        category: ECategory.TECHNOLOGY,
        author: mockUsers[2], // Mike Johnson (Admin)
        createdAt: "2024-01-13T15:00:00Z",
        updatedAt: "2024-01-13T15:00:00Z",
    },
    {
        id: "blog-9",
        title: "Mental Health Awareness: Breaking the Stigma",
        description: "Understanding and addressing mental health in modern society",
        content: "Mental health is as important as physical health, yet stigma continues to prevent many from seeking help. This article explores common mental health conditions, the importance of seeking professional support, and how society can create a more understanding environment...",
        thumbnailUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=400&fit=crop",
        category: ECategory.HEALTH,
        author: mockUsers[9], // Amanda Taylor
        createdAt: "2024-01-09T12:00:00Z",
        updatedAt: "2024-01-09T12:00:00Z",
    },
    {
        id: "blog-10",
        title: "Personal Finance Management Tips",
        description: "Smart strategies for saving, investing, and achieving financial freedom",
        content: "Financial literacy is crucial for long-term success and security. Learn practical tips for budgeting, building an emergency fund, investing wisely, and planning for retirement. These fundamental principles can help anyone take control of their financial future...",
        thumbnailUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=400&fit=crop",
        category: ECategory.FINANCE,
        author: mockUsers[4], // David Brown
        createdAt: "2024-01-07T10:45:00Z",
        updatedAt: "2024-01-07T10:45:00Z",
    },
];


